name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # main 브랜치에 푸시되면 이 워크플로우가 트리거됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.10.0' # Strapi에 적합한 Node.js 버전을 선택하세요.

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install

    - name: Copy files to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      run: chmod 600 /home/runner/.ssh/deploy_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: '.'
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # EC2 인스턴스의 IP 주소 또는 도메인
        REMOTE_USER: ${{ secrets.REMOTE_USER }} # EC2 인스턴스의 사용자 이름
        TARGET: ${{ secrets.REMOTE_TARGET }} # 파일을 복사할 EC2 인스턴스의 경로
        
    - name: Set Execution Permissions
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "chmod +x ~/services/komponents-backend/deploy.sh"

    - name: Execute Deployment Script
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "~/services/komponents-backend/deploy.sh"
